[project]
authors = ["Nedy88 <nedy88@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mantis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
black = ">=24.10.0,<25"

[pypi-dependencies]
jax = { version = ">=0.4.35, <0.5", extras = ["cuda"] }
flax = ">=0.10.2, <0.11"
ruff = ">=0.8.0, <0.9"
