defaults:
  - transformer: base
  - dataset: caltech-256
  - _self_

patch_size: 16
float32_matmul_precision: high
num_nodes: 1
gpus_per_node: 8
num_workers: 4
epochs: 1000
log_every_n_steps: 50
batch_size: 128
learning:
  lr: 5e-4
  weight_decay: 0.01
  min_lr: 1e-6
  warmup_epochs: 50
  accum_iter: 1

hydra:
  output_subdir: null
  run:
    dir: .
